site_name: Byte
theme:
  name: material
  logo: images/assets/logo-square.svg
  favicon: images/assets/favicon.ico
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate
    primary: black

repo_url: https://github.com/UseTheFork/byte
repo_name: byte
site_author: UseTheFork
site_url: https://usethefork.github.io/byte/
site_dir: site/byte
site_description: A CLI coding agent built for efficiency, not autonomy.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - toc:
      anchorlink: true
      anchorlink_class: "toclink"
  - md_in_html:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Tutorials:
    - Getting Started:
      - Installation: tutorials/getting-started/installation.md
  - How-to Guides:
    - Adding Files: how-to-guides/adding-files.md
    - Configure Linting: how-to-guides/configuring-linting.md
    - Configure Providers / Models: how-to-guides/configure-providers-models.md
    - Create & Manage Skills: how-to-guides/creating-and-managing-skills.md
    - Create & Manage Specs: how-to-guides/creating-and-managing-specs.md
    - Create AI-Powered Git Commits: how-to-guides/using-git-commits.md
    - Manage File Context: how-to-guides/managing-file-context.md
    - Manage Web Context: how-to-guides/managing-web-context.md
    - Manage the Constitution: how-to-guides/managing-the-constitution.md
  - Explanation:
    - Architecture Overview: explanation/architecture-overview.md
    - Configuration: explanation/configuration.md
    - The Constitution: explanation/the-constitution.md
    - The Gateway: explanation/the-gateway.md
    - The Commands: explanation/the-commands.md


plugins:
- search
- mkdocstrings
- include-markdown

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
