from byte.core.utils.list_to_multiline_text import list_to_multiline_text

edit_format_system = list_to_multiline_text(
    [
        "# *Pseudo-XML Edit Block* Rules:",
        "",
        "Use *Pseudo-XML edit blocks* to make precise edits to files. Each block specifies:",
        "- **What file** to modify (with full path)",
        "- **What operation** to perform (edit, create, delete, replace)",
        "- **What content** to find (search section)",
        "- **What to replace** it with (replace section)",
        "",
        "## Block Format:",
        "",
        "Every *Pseudo-XML edit block* must use this exact format:",
        "```language",
        '<file path="full/file/path" operation="operation_type">',
        "<search>",
        "content to find (can be empty)",
        "</search>",
        "<replace>",
        "content to replace with (can be empty)",
        "</replace>",
        "</file>",
        "```",
        "",
        "## Operation Types:",
        "- `edit` for **editing** existing file content",
        "- `create` for **creating** new files",
        "- `delete` for **removing** files completely",
        "- `replace` for **replacing entire file contents**",
        "",
        "## Examples:",
        "",
        "**Create a new file:**",
        "```python",
        '<file path="mathweb/flask/app.py" operation="create">',
        "<search>",
        "</search>",
        "<replace>",
        "import math",
        "from flask import Flask",
        "</replace>",
        "</file>",
        "```",
        "",
        "**Edit existing file content:**",
        "```python",
        '<file path="mathweb/flask/app.py" operation="edit">',
        "<search>",
        "from flask import Flask",
        "</search>",
        "<replace>",
        "import math",
        "from flask import Flask",
        "</replace>",
        "</file>",
        "```",
        "",
        "**Remove entire file:**",
        "```python",
        '<file path="old_config.py" operation="delete">',
        "<search>",
        "</search>",
        "<replace>",
        "</replace>",
        "</file>",
        "```",
        "",
        "**Replace all file contents:**",
        "```python",
        '<file path="config.py" operation="replace">',
        "<search>",
        "</search>",
        "<replace>",
        "import os",
        "from dataclasses import dataclass",
        "",
        "@dataclass",
        "class AppConfig:",
        "    debug: bool = False",
        "    port: int = 8000",
        '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
        "</replace>",
        "</file>",
        "```",
        "",
        "## **CRITICAL RULES:**",
        "",
        "File Paths:",
        "- Use the FULL file path exactly as shown by the user",
        "- No bold asterisks, quotes, or escaping around the path",
        "",
        "Search Content:",
        "- Must EXACTLY MATCH existing file content, character for character",
        "- Include all comments, docstrings, whitespace, etc.",
        "- If file contains wrapped/escaped content, match the literal file contents",
        "",
        "Block Strategy:",
        "- Keep blocks small and focused",
        "- Use multiple blocks for multiple changes to the same file",
        "- Include enough context lines to make each search unique",
        "- Only replace the first occurrence found",
        "",
        "File Operations:",
        "- Only edit files that the user has added to the chat",
        '- For new files: use operation="create" with empty search, content in replace',
        "- To move code: use 2 blocks (1 to delete, 1 to insert)",
        "",
        "User Intent:",
        '- If user says "ok", "go ahead", or "do that" → provide Pseudo-XML edit blocks',
        "- Wait for user confirmation before assuming edits are applied",
        "- ONLY EVER RETURN CODE IN A PSEUDO-XML EDIT BLOCK!",
    ]
)

practice_messages = [
    (
        "user",
        list_to_multiline_text(
            [
                "Before we start lets first practice the *Pseudo-XML edit block* format.",
                "",
                "Change get_factorial() to use math.factorial",
            ]
        ),
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To make this change we need to modify `mathweb/flask/app.py` to:",
                "",
                "1. Import the math package.",
                "2. Remove the existing factorial() function.",
                "3. Update get_factorial() to call math.factorial instead.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                '<file path="mathweb/flask/app.py" operation="edit">',
                "<search>",
                "from flask import Flask",
                "</search>",
                "<replace>",
                "import math",
                "from flask import Flask",
                "</replace>",
                "</file>",
                "```",
                "",
                "```python",
                '<file path="mathweb/flask/app.py" operation="edit">',
                "<search>",
                "def factorial(n):",
                '    "compute factorial"',
                "",
                "    if n == 0:",
                "        return 1",
                "    else:",
                "        return n * factorial(n-1)",
                "",
                "</search>",
                "<replace>",
                "</replace>",
                "</file>",
                "```",
                "",
                "```python",
                '<file path="mathweb/flask/app.py" operation="edit">',
                "<search>",
                "    return str(factorial(n))",
                "</search>",
                "<replace>",
                "    return str(math.factorial(n))",
                "</replace>",
                "</file>",
                "```",
            ]
        ),
    ),
    (
        "user",
        "Refactor hello() into its own file.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To make this change we need to modify `main.py` and make a new file `hello.py`:",
                "",
                "1. Make a new hello.py file with hello() in it.",
                "2. Remove hello() from main.py and replace it with an import.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                '<file path="hello.py" operation="create">',
                "<search>",
                "</search>",
                "<replace>",
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                "</replace>",
                "</file>",
                "```",
                "",
                "```python",
                '<file path="main.py" operation="edit">',
                "<search>",
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                "</search>",
                "<replace>",
                "from hello import hello",
                "</replace>",
                "</file>",
                "```",
            ]
        ),
    ),
    ("user", "Remove the old_config.py file that's no longer needed."),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To remove this file we need to delete `old_config.py`:",
                "",
                "1. Remove the old_config.py file completely from the project.",
                "",
                "Here is the *Pseudo-XML edit* block:",
                "",
                "```python",
                '<file path="old_config.py" operation="delete">',
                "<search>",
                "</search>",
                "<replace>",
                "</replace>",
                "</file>",
                "```",
            ]
        ),
    ),
    (
        "user",
        "Replace all the contents of config.py with a new configuration structure.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To replace all the contents we need to completely rewrite `config.py`:",
                "",
                "1. Replace the entire contents of config.py with the new configuration structure.",
                "",
                "Here is the *Pseudo-XML edit* block:",
                "",
                "```python",
                '<file path="config.py" operation="replace">',
                "<search>",
                "</search>",
                "<replace>",
                "import os",
                "from dataclasses import dataclass",
                "",
                "@dataclass",
                "class AppConfig:",
                "    debug: bool = False",
                "    port: int = 8000",
                '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
                "</replace>",
                "</file>",
                "```",
            ]
        ),
    ),
    (
        "user",
        "Add error handling to the calculator function and update the docstring.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                "To add error handling we need to modify `calculator.py` in two places:",
                "",
                "1. Update the docstring to mention error handling.",
                "2. Add try-catch block around the calculation.",
                "",
                "Here are the *Pseudo-XML edit* blocks:",
                "",
                "```python",
                '<file path="calculator.py" operation="edit">',
                "<search>",
                "def calculate(a, b):",
                '    "Simple calculator function"',
                "</search>",
                "<replace>",
                "def calculate(a, b):",
                '    "Simple calculator function with error handling"',
                "</replace>",
                "</file>",
                "```",
                "",
                "```python",
                '<file path="calculator.py" operation="edit">',
                "<search>",
                "    return a / b",
                "</search>",
                "<replace>",
                "    try:",
                "        return a / b",
                "    except ZeroDivisionError:",
                '        return "Error: Cannot divide by zero"',
                "</replace>",
                "</file>",
                "```",
            ]
        ),
    ),
]
