from byte.code_operations import EDIT_BLOCK_NAME, Boundary, BoundaryType
from byte.code_operations.schemas import AICommentType
from byte.support.utils import list_to_multiline_text

edit_format_system = list_to_multiline_text(
    [
        Boundary.open(BoundaryType.RESPONSE_FORMAT),
        f"# *{EDIT_BLOCK_NAME}* Rules:",
        "",
        f"Use *{EDIT_BLOCK_NAME}* to make precise edits to the repo. Each {EDIT_BLOCK_NAME} specifies:",
        "- **What repo file** to modify (with full path)",
        "- **What operation** to perform (edit, create, delete, replace)",
        "- **What content** to find (search section)",
        "- **What to replace** it with (replace section)",
        "",
        "## Response Structure:",
        "",
        f"**REQUIRED**: All responses containing *{EDIT_BLOCK_NAME}* MUST start with a PLAN section:",
        "",
        f"- Wrap your plan in `{Boundary.open(BoundaryType.PLAN)}...{Boundary.close(BoundaryType.PLAN)}` boundaries",
        "- Explain what files will be modified and why",
        "- List the specific changes in numbered steps",
        "- Keep it concise but complete",
        "",
        "Example:",
        Boundary.open(BoundaryType.PLAN) + Boundary.notice("new line here"),
        "To make this change we need to modify `mathweb/flask/app.py` to:",
        "",
        "1. Import the math package.",
        "2. Remove the existing factorial() function.",
        "3. Update get_factorial() to call math.factorial instead.",
        Boundary.close(BoundaryType.PLAN) + Boundary.notice("new line here"),
        "",
        f"## *{EDIT_BLOCK_NAME}* Format:",
        "",
        f"Every *{EDIT_BLOCK_NAME}* must use this exact format:",
        "```language",
        Boundary.open(
            BoundaryType.FILE, meta={"path": "full/file/path", "operation": "operation_type", "block_id": "1"}
        ),
        Boundary.open(BoundaryType.SEARCH) + Boundary.notice("new line here"),
        "[exact charector for charector content to find"
        + Boundary.notice("(including comments and ai messages, can be empty)"),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE) + Boundary.notice("new line here"),
        "[content to replace with]" + Boundary.notice("(can be empty)"),
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "**IMPORTANT**: Never put content on the same line as the opening tag.",
        "",
        "## Operation Types:",
        "- `edit` for **editing** existing file content",
        "- `create` for **creating** new files",
        "- `delete` for **removing** files completely",
        "- `replace` for **replacing entire file contents**",
        "",
        "## Examples:",
        "",
        "**Create a new file:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "create", "block_id": "1"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import math",
        "from flask import Flask",
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Edit existing file content:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit", "block_id": "1"}),
        Boundary.open(BoundaryType.SEARCH),
        "from flask import Flask",
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import math",
        "from flask import Flask",
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Remove entire file:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "old_config.py", "operation": "delete", "block_id": "1"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "**Replace all file contents:**",
        "```python",
        Boundary.open(BoundaryType.FILE, meta={"path": "config.py", "operation": "replace", "block_id": "1"}),
        Boundary.open(BoundaryType.SEARCH),
        Boundary.close(BoundaryType.SEARCH),
        Boundary.open(BoundaryType.REPLACE),
        "import os",
        "from dataclasses import dataclass",
        "",
        "@dataclass",
        "class AppConfig:",
        "    debug: bool = False",
        "    port: int = 8000",
        '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
        Boundary.close(BoundaryType.REPLACE),
        Boundary.close(BoundaryType.FILE),
        "```",
        "",
        "## **CRITICAL RULES:**",
        "File Paths:",
        "- Use the FULL file path exactly as shown by the user",
        "- No bold asterisks, quotes, or escaping around the path",
        "",
        "Search Content:",
        "- Must EXACTLY MATCH existing file content, character for character",
        "- Include all comments, docstrings, whitespace, etc.",
        "- If file contains wrapped/escaped content, match the literal file contents",
        "",
        "Block Strategy:",
        "- Use multiple blocks for multiple changes to the same file",
        "- Include enough context lines to make each search unique",
        "- Only replace the first occurrence found",
        "",
        "File Operations:",
        f"- Only edit files that the user has added to the chat. Refer to `{Boundary.open(BoundaryType.CONTEXT, meta={'type': 'editable files'})}`",
        '- For new files: use operation="create" with empty search, content in replace',
        f"- To move code: use 2 {EDIT_BLOCK_NAME} (1 to delete, 1 to insert)",
        "",
        "User Intent:",
        f'- If user says "ok", "go ahead", or "do that" → provide {EDIT_BLOCK_NAME}',
        "- Wait for user confirmation before assuming edits are applied",
        f"- ONLY EVER RETURN CODE IN A {EDIT_BLOCK_NAME}!",
        "",
        Boundary.close(BoundaryType.RESPONSE_FORMAT),
        Boundary.open(BoundaryType.USER_INPUT),
        f"Before we start lets first practice the *{EDIT_BLOCK_NAME}* Block format.",
        "",
        "Change get_factorial() to use math.factorial",
        Boundary.close(BoundaryType.USER_INPUT),
    ]
)

edit_format_enforcement = [
    Boundary.open(BoundaryType.SEARCH) + " Tag Rules:",
    "- Never put content on the same line as the opening tag.",
    f"- Must EXACTLY MATCH existing file content, character for character including comments and {AICommentType.AI.value} comments.",
]

edit_format_recovery_steps = list_to_multiline_text(
    [
        Boundary.close(BoundaryType.RECOVERY_STEPS),
        'If you get "search string not found in file":',
        "1. **View the file again** at the specific location",
        "2. **Copy more context** - include entire function if needed",
        "3. **Check whitespace**:",
        "   - Count indentation spaces/tabs",
        "   - Look for blank lines",
        "   - Check for trailing spaces",
        "4. **Verify character-by-character** that your search block matches",
        "5. **Never guess** - always View the file to get exact text",
        "",
        f"ALWAYS respond with the original message and ALL of the {EDIT_BLOCK_NAME} Blocks.",
        " Note: The message you respond with will be the ones stored in conversation history.",
        Boundary.close(BoundaryType.RECOVERY_STEPS),
    ]
)

shell_command_system = list_to_multiline_text(
    [
        "# *Shell Command Block* Rules:",
        "Use *Shell Command blocks* to execute shell commands AFTER file edits are applied.",
        "",
        "Just suggest shell commands this way, not example code.",
        "Only suggest complete shell commands that are ready to execute, without placeholders.",
        "Only suggest at most a few shell commands at a time, not more than 1-3, one per line.",
        "Do not suggest multi-line shell commands.",
        "All shell commands will run from the root directory of the user's project.",
        "",
        "## Block Format:",
        "",
        "```sh",
        Boundary.open(BoundaryType.SHELL_COMMAND),
        "command to execute",
        Boundary.close(BoundaryType.SHELL_COMMAND),
        "```",
        "Or:",
        "```bash",
        Boundary.open(BoundaryType.SHELL_COMMAND),
        "command to execute",
        "second command to execute",
        Boundary.close(BoundaryType.SHELL_COMMAND),
        "```",
        "",
        "## **CRITICAL RULES:**",
        "",
        "When to Use:",
        "- If you changed a CLI program, suggest the command to run it to see the new behavior.",
        "- If you added a test, suggest how to run it with the testing tool used by the project.",
        "- If your code changes add new dependencies, suggest the command to install them.",
        "- Never edit files with shell commands (echo, sed, >>) - use SEARCH/REPLACE instead",
        "",
        "Safety:",
        "- Commands require user confirmation before execution",
        "- Dangerous operations prompt for explicit approval",
        "",
        "Execution:",
        "- Execute AFTER all SEARCH/REPLACE blocks succeed",
        "- Execute sequentially in order they appear",
        "- If file edits fail, shell commands are skipped",
    ]
)

practice_messages = [
    ("user", edit_format_system),
    (
        "assistant",
        list_to_multiline_text(
            [
                Boundary.open(BoundaryType.PLAN),
                "To make this change we need to modify `mathweb/flask/app.py` to:",
                "",
                "1. Import the math package.",
                "2. Remove the existing factorial() function.",
                "3. Update get_factorial() to call math.factorial instead.",
                Boundary.close(BoundaryType.PLAN),
                "",
                "```python",
                Boundary.open(
                    BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit", "block_id": "1"}
                ),
                Boundary.open(BoundaryType.SEARCH),
                "from flask import Flask",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "import math",
                "from flask import Flask",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(
                    BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit", "block_id": "2"}
                ),
                Boundary.open(BoundaryType.SEARCH),
                "def factorial(n):",
                '    "compute factorial"',
                "",
                "    if n == 0:",
                "        return 1",
                "    else:",
                "        return n * factorial(n-1)",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(
                    BoundaryType.FILE, meta={"path": "mathweb/flask/app.py", "operation": "edit", "block_id": "3"}
                ),
                Boundary.open(BoundaryType.SEARCH),
                "    return str(factorial(n))",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "    return str(math.factorial(n))",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Refactor hello() into its own file.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                Boundary.open(BoundaryType.PLAN),
                "To make this change we need to modify `main.py` and make a new file `hello.py`:",
                "",
                "1. Make a new hello.py file with hello() in it.",
                "2. Remove hello() from main.py and replace it with an import.",
                Boundary.close(BoundaryType.PLAN),
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "hello.py", "operation": "create", "block_id": "1"}),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "main.py", "operation": "edit", "block_id": "2"}),
                Boundary.open(BoundaryType.SEARCH),
                "def hello():",
                '    "print a greeting"',
                "",
                '    print("hello")',
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "from hello import hello",
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    ("user", "Remove the old_config.py file that's no longer needed."),
    (
        "assistant",
        list_to_multiline_text(
            [
                Boundary.open(BoundaryType.PLAN),
                "To remove this file we need to delete `old_config.py`:",
                "",
                "1. Remove the old_config.py file completely from the project.",
                Boundary.close(BoundaryType.PLAN),
                "",
                "```python",
                Boundary.open(
                    BoundaryType.FILE, meta={"path": "old_config.py", "operation": "delete", "block_id": "1"}
                ),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Replace all the contents of config.py with a new configuration structure.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                Boundary.open(BoundaryType.PLAN),
                "To replace all the contents we need to completely rewrite `config.py`:",
                "",
                "1. Replace the entire contents of config.py with the new configuration structure.",
                Boundary.close(BoundaryType.PLAN),
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "config.py", "operation": "replace", "block_id": "1"}),
                Boundary.open(BoundaryType.SEARCH),
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "import os",
                "from dataclasses import dataclass",
                "",
                "@dataclass",
                "class AppConfig:",
                "    debug: bool = False",
                "    port: int = 8000",
                '    database_url: str = os.getenv("DATABASE_URL", "sqlite:///app.db")',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
    (
        "user",
        "Add error handling to the calculator function and update the docstring.",
    ),
    (
        "assistant",
        list_to_multiline_text(
            [
                Boundary.open(BoundaryType.PLAN),
                "To add error handling we need to modify `calculator.py` in two places:",
                "",
                "1. Update the docstring to mention error handling.",
                "2. Add try-catch block around the calculation.",
                Boundary.close(BoundaryType.PLAN),
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "calculator.py", "operation": "edit", "block_id": "1"}),
                Boundary.open(BoundaryType.SEARCH),
                "def calculate(a, b):",
                '    "Simple calculator function"',
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "def calculate(a, b):",
                '    "Simple calculator function with error handling"',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
                "",
                "```python",
                Boundary.open(BoundaryType.FILE, meta={"path": "calculator.py", "operation": "edit", "block_id": "2"}),
                Boundary.open(BoundaryType.SEARCH),
                "    return a / b",
                Boundary.close(BoundaryType.SEARCH),
                Boundary.open(BoundaryType.REPLACE),
                "    try:",
                "        return a / b",
                "    except ZeroDivisionError:",
                '        return "Error: Cannot divide by zero"',
                Boundary.close(BoundaryType.REPLACE),
                Boundary.close(BoundaryType.FILE),
                "```",
            ]
        ),
    ),
]

# pseudo_xml_prompts = EditFormatPrompts(
#     system=edit_format_system,
#     examples=practice_messages,
#     shell_system=shell_command_system,
#     shell_examples=[],
# )
